# Generated by Django 3.2.8 on 2022-01-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0005_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
