# Generated by Django 3.2.8 on 2022-01-12 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0009_alter_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='child',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='my_blog.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_blog.comment'),
        ),
    ]
